[0m[[0mdebug[0m] [0mRunning TaskDef(irobo.api.service.UrlServiceTest, utest.runner.Framework$$anon$1@4b3759b5, false, [SuiteSelector])[0m
[0m[[0minfo[0m] [0mScalaCheck[0m
[0m[[0minfo[0m] [0mPassed: Total 0, Failed 0, Errors 0, Passed 0[0m
[0m[[0minfo[0m] [0mScalaTest[0m
[0m[[0minfo[0m] [0m[36mRun completed in 890 milliseconds.[0m[0m
[0m[[0minfo[0m] [0m[36mTotal number of tests run: 0[0m[0m
[0m[[0minfo[0m] [0m[36mSuites: completed 0, aborted 0[0m[0m
[0m[[0minfo[0m] [0m[36mTests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0[0m[0m
[0m[[0minfo[0m] [0m[33mNo tests were executed.[0m[0m
[0m[[0minfo[0m] [0mutest[0m
[0m[[0minfo[0m] [0m-----------------------------------Results-----------------------------------[0m
[0m[[0minfo[0m] [0mirobo.api.service.UrlServiceTest		[32mSuccess[0m[0m
[0m[[0minfo[0m] [0m    Url Service Test		[32mSuccess[0m[0m
[0m[[0minfo[0m] [0m        get hashed full url		[31mFailure('org.scalatest.exceptions.TestFailedException: "098F6BCD4621D373CADE4E832627B4F6" did not equal None')[0m[0m
[0m[[0minfo[0m] [0m        to base 62		[31mFailure('org.scalatest.exceptions.TestFailedException: Some("3N0") did not equal None')[0m[0m
[0m[[0minfo[0m] [0m        to base 10		[31mFailure('org.scalatest.exceptions.TestFailedException: 125 did not equal None')[0m[0m
[0m[[0minfo[0m] [0m        get short url		[32mSuccess[0m[0m
[0m[[0minfo[0m] [0m        get full url		[31mFailure('org.scalatest.exceptions.TestFailedException: Some("www.naver.com") did not equal None')[0m[0m
[0m[[0minfo[0m] [0m[31mFailures:[0m
[0m[[0minfo[0m] [0mirobo.api.service.UrlServiceTest.Url Service Test.get hashed full url		[31m[0m
[0m[[0minfo[0m] [0m                   		[31morg.scalatest.exceptions.TestFailedException: "098F6BCD4621D373CADE4E832627B4F6" did not equal None[0m[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$.newAssertionFailedException(UrlServiceTest.scala:18)[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$3.apply(UrlServiceTest.scala:41)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$3.apply(UrlServiceTest.scala:19)[0m
[0m[[0minfo[0m] [0mirobo.api.service.UrlServiceTest.Url Service Test.to base 62		[31m[0m
[0m[[0minfo[0m] [0m          		[31morg.scalatest.exceptions.TestFailedException: Some("3N0") did not equal None[0m[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$.newAssertionFailedException(UrlServiceTest.scala:18)[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$4.apply(UrlServiceTest.scala:47)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$4.apply(UrlServiceTest.scala:19)[0m
[0m[[0minfo[0m] [0mirobo.api.service.UrlServiceTest.Url Service Test.to base 10		[31m[0m
[0m[[0minfo[0m] [0m          		[31morg.scalatest.exceptions.TestFailedException: 125 did not equal None[0m[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$.newAssertionFailedException(UrlServiceTest.scala:18)[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$5.apply(UrlServiceTest.scala:53)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$5.apply(UrlServiceTest.scala:19)[0m
[0m[[0minfo[0m] [0mirobo.api.service.UrlServiceTest.Url Service Test.get full url		[31m[0m
[0m[[0minfo[0m] [0m            		[31morg.scalatest.exceptions.TestFailedException: Some("www.naver.com") did not equal None[0m[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:500)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$.newAssertionFailedException(UrlServiceTest.scala:18)[0m
[0m[[0minfo[0m] [0m[31morg.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:466)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$9$$anonfun$apply$10.apply(UrlServiceTest.scala:68)[0m
[0m[[0minfo[0m] [0m[31mirobo.api.service.UrlServiceTest$$anonfun$7$$anonfun$apply$1$$anonfun$apply$9$$anonfun$apply$10.apply(UrlServiceTest.scala:67)[0m
[0m[[0minfo[0m] [0m[31mscala.util.Success$$anonfun$map$1.apply(Try.scala:237)[0m
[0m[[0minfo[0m] [0m[31mscala.util.Try$.apply(Try.scala:192)[0m
[0m[[0minfo[0m] [0m[31mscala.util.Success.map(Try.scala:237)[0m
[0m[[0minfo[0m] [0m[31mscala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)[0m
[0m[[0minfo[0m] [0m[31mscala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)[0m
[0m[[0minfo[0m] [0m[31mscala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)[0m
[0m[[0minfo[0m] [0m[31mjava.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[0m
[0m[[0minfo[0m] [0m[31mjava.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[0m
[0m[[0minfo[0m] [0m[31mjava.lang.Thread.run(Thread.java:748)[0m
[0m[[0minfo[0m] [0mTests: 7[0m
[0m[[0minfo[0m] [0mPassed: 3[0m
[0m[[0minfo[0m] [0mFailed: 4[0m
[0m[[31merror[0m] [0mFailed: Total 11, Failed 4, Errors 0, Passed 7[0m
[0m[[31merror[0m] [0mFailed tests:[0m
[0m[[31merror[0m] [0m	irobo.api.service.UrlServiceTest[0m
[0m[[31merror[0m] [0m(test:[31mtestOnly[0m) sbt.TestsFailedException: Tests unsuccessful[0m
